<a href="https://colab.research.google.com/github/Chandrashekar0123/Lerno-ML-case-study/blob/main/K_Means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

K-Means Clustering Algorithm without and with
Normalization


In [14]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
%matplotlib inline


In [ ]:
customers_df = pd.read_csv("/content/income-age.csv")


In [ ]:

customers_df


income    age
0    41100.0  48.75
1    54100.0  28.10
2    47800.0  46.75
3    19100.0  40.25
4    18200.0  35.80
..       ...    ...
295  38300.0  46.10
296  27400.0  44.15
297  54200.0  28.25
298  41800.0  44.85
299  38600.0  39.35

[300 rows x 2 columns]

In [ ]:
customers_df.head(5)


income    age
0  41100.0  48.75
1  54100.0  28.10
2  47800.0  46.75
3  19100.0  40.25
4  18200.0  35.80

In [6]:
from sklearn.cluster import KMeans
clusters = KMeans(3)
clusters.fit(customers_df)


KMeans(n_clusters=3)

In [10]:

customers_df["clusterid"] = clusters.labels_


In [11]:
clusters.labels_

array([0, 2, 0, 1, 1, 1, 2, 0, 1, 0, 2, 2, 2, 0, 2, 1, 0, 0, 1, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2, 1, 0, 0, 2, 2, 1, 2, 1, 0, 2, 1, 2, 0, 2,
       2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2, 0, 1, 2, 1,
       0, 2, 0, 2, 1, 0, 1, 1, 2, 0, 2, 1, 0, 0, 1, 0, 2, 0, 0, 2, 2, 1,
       0, 0, 1, 2, 1, 2, 2, 2, 0, 2, 1, 0, 2, 1, 0, 2, 2, 2, 1, 0, 2, 2,
       0, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1,
       0, 1, 1, 2, 1, 0, 1, 1, 2, 0, 2, 0, 1, 1, 0, 1, 1, 2, 0, 1, 0, 2,
       1, 1, 2, 2, 0, 2, 0, 2, 2, 0, 1, 2, 0, 0, 0, 1, 2, 0, 1, 2, 2, 2,
       0, 2, 0, 2, 2, 1, 0, 0, 0, 0, 2, 1, 0, 1, 0, 0, 2, 2, 1, 0, 2, 1,
       0, 1, 2, 1, 2, 1, 2, 1, 0, 1, 0, 2, 0, 0, 1, 2, 2, 2, 2, 0, 1, 2,
       0, 2, 2, 2, 0, 1, 1, 0, 2, 0, 0, 2, 2, 0, 2, 1, 1, 1, 0, 0, 2, 1,
       1, 1, 1, 2, 0, 1, 0, 2, 2, 0, 2, 2, 1, 0, 2, 1, 2, 2, 1, 2, 1, 1,
       0, 1, 0, 2, 2, 2, 2, 0, 0, 0, 2, 2, 1, 1, 2, 2, 0, 2, 2, 2, 1, 2,
       1, 1, 2, 2, 1, 1, 0, 2, 0, 0, 1, 2, 0, 0], d

In [12]:

customers_df

income    age  clusterid
0    41100.0  48.75          0
1    54100.0  28.10          2
2    47800.0  46.75          0
3    19100.0  40.25          1
4    18200.0  35.80          1
..       ...    ...        ...
295  38300.0  46.10          0
296  27400.0  44.15          1
297  54200.0  28.25          2
298  41800.0  44.85          0
299  38600.0  39.35          0

[300 rows x 3 columns]

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()
scaled_customers_df = scaler.fit_transform(customers_df[["age","income"]])
scaled_customers_df[0:5]


array([[ 1.3701637 ,  0.09718548],
       [-1.3791283 ,  0.90602749],
       [ 1.10388844,  0.51405021],
       [ 0.23849387, -1.27162408],
       [-0.35396857, -1.32762083]])

In [23]:
customers_df


income    age  clusterid
0    41100.0  48.75          0
1    54100.0  28.10          2
2    47800.0  46.75          0
3    19100.0  40.25          1
4    18200.0  35.80          1
..       ...    ...        ...
295  38300.0  46.10          0
296  27400.0  44.15          1
297  54200.0  28.25          2
298  41800.0  44.85          0
299  38600.0  39.35          0

[300 rows x 3 columns]

In [24]:

customers_df[["age","income"]]


age   income
0    48.75  41100.0
1    28.10  54100.0
2    46.75  47800.0
3    40.25  19100.0
4    35.80  18200.0
..     ...      ...
295  46.10  38300.0
296  44.15  27400.0
297  28.25  54200.0
298  44.85  41800.0
299  39.35  38600.0

[300 rows x 2 columns]

In [25]:
scaled_customers_df

array([[ 1.3701637 ,  0.09718548],
       [-1.3791283 ,  0.90602749],
       [ 1.10388844,  0.51405021],
       [ 0.23849387, -1.27162408],
       [-0.35396857, -1.32762083],
       [ 0.39825902, -1.22807105],
       [-0.91980349,  0.74425909],
       [ 1.296938  ,  0.02252314],
       [-0.22083094, -1.65115764],
       [ 0.61127922, -0.47522579],
       [-1.1661081 ,  0.75670281],
       [-1.22602003,  1.06779589],
       [-1.17276498,  1.19845499],
       [ 1.16380038,  0.43316601],
       [-1.34584389,  0.96202425],
       [ 0.35831773, -1.32762083],
       [ 0.89086824,  0.42694415],
       [ 0.77770126,  0.42072228],
       [ 1.09057468, -1.08496823],
       [-1.25930443,  0.85003074],
       [ 0.23183699, -1.42094876],
       [ 0.84427007,  0.4020567 ],
       [-1.23267691,  0.85003074],
       [ 1.17711414,  0.10340734],
       [-0.26077223, -1.96225072],
       [ 0.06541495, -1.63871392],
       [ 0.69781868,  0.06607617],
       [-0.01446762, -1.68226695],
       [-1.14613745,

In [26]:
from sklearn.cluster import KMeans
clusters_new = KMeans(3, random_state=42)
clusters_new.fit(scaled_customers_df)
customers_df["clusterid_new"] = clusters_new.labels_


In [27]:
clusters_new.labels_


array([0, 1, 0, 2, 2, 2, 1, 0, 2, 0, 1, 1, 1, 0, 1, 2, 0, 0, 2, 1, 2, 0,
       1, 0, 2, 2, 0, 2, 1, 1, 2, 0, 0, 1, 1, 2, 1, 2, 0, 1, 2, 1, 0, 1,
       1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 1, 1, 0, 2, 1, 2,
       0, 1, 0, 1, 2, 0, 2, 2, 1, 0, 1, 2, 0, 0, 2, 0, 1, 0, 0, 0, 1, 2,
       0, 0, 2, 1, 2, 0, 1, 1, 0, 1, 2, 0, 1, 2, 0, 1, 0, 0, 2, 0, 1, 1,
       0, 2, 0, 0, 2, 2, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2,
       0, 2, 2, 1, 2, 0, 2, 2, 1, 0, 1, 0, 2, 2, 0, 2, 2, 1, 0, 2, 0, 1,
       2, 2, 1, 1, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 1,
       0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 1, 1, 2, 0, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 2, 0, 2, 0, 1, 0, 0, 2, 1, 1, 1, 1, 0, 2, 1,
       0, 1, 1, 1, 0, 2, 2, 0, 0, 2, 0, 1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2,
       2, 2, 2, 1, 2, 2, 0, 1, 1, 0, 1, 1, 2, 0, 1, 2, 0, 0, 2, 0, 2, 2,
       0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 1, 1, 1, 2, 1,
       2, 2, 1, 1, 2, 2, 2, 1, 0, 0, 2, 1, 0, 0], d

In [28]:

customers_df

income    age  clusterid  clusterid_new
0    41100.0  48.75          0              0
1    54100.0  28.10          2              1
2    47800.0  46.75          0              0
3    19100.0  40.25          1              2
4    18200.0  35.80          1              2
..       ...    ...        ...            ...
295  38300.0  46.10          0              0
296  27400.0  44.15          1              2
297  54200.0  28.25          2              1
298  41800.0  44.85          0              0
299  38600.0  39.35          0              0

[300 rows x 4 columns]

In [29]:
clusters.cluster_centers_


array([[4.25761364e+04, 4.63562500e+01],
       [1.78851064e+04, 3.90808511e+01],
       [5.45211864e+04, 3.20733051e+01]])

In [32]:

sn.lmplot("age", "income", data = customers_df,hue = "clusterid_new",
 fit_reg = False,markers = markers,size = 4);

customers_df.groupby( "clusterid")["age","income"].agg(
 ["mean","std"]).reset_index()
 #use this code to get visual representation of clusters

'markers = ["+","^","."]\n\nsn.lmplot("age", "income", data = customers_df,hue = "clusterid_new",\n fit_reg = False,markers = markers,size = 4);\n\ncustomers_df.groupby( "clusterid")["age","income"].agg(\n ["mean","std"]).reset_index()'